### ISSUE TITLE
Mount /Users on startup

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root-xhyve#1]
First off thanks so much for this project!

When issuing "make up", I see on the console line that will be added to /etc/exports on the Mac:

```
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=501:20
```

I also see that in the docker VM that /mnt/vda1/var/lib/docker-root/start.sh appears to mount /Users.

However I need to explicitly call it (or issue an mount myself) in order to have /Users mounted. Is there a reason that it is not run automatically?

Thanks

**Comment by ailispaw** [comment]
Hi @if-kenn ,
Hmm. It can't be. It's just fine on my side.

Please check `/var/log/messages`.
Can you see `init[1]: Starting custom script start.sh` line there?

**Comment by if-kenn** [comment]
I do see it:

Sep 24 22:07:03 docker-root user.info init[1]: Starting custom script start.sh

**Comment by ailispaw** [comment]
I see. That means the start.sh was executed.
Something wrong...

**Comment by ailispaw** [comment]
Do you run DockerRoot v1.0.4?

**Comment by if-kenn** [comment]
"Welcome to DockerRoot version 1.0.4, Docker version 1.8.2, build 0a8c2e3"

Followed steps on this page https://github.com/ailispaw/docker-root-xhyve
1. brew install xhyve
2. git clone https://github.com/ailispaw/docker-root-xhyve
3. cd docker-root-xhyve
4. make init

I just noticed a segfault after doing a "sudo halt" and then a "make up" again:

```
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=501:20
rdmsr to register 0x570 on vcpu 0

Welcome to DockerRoot docker-root /dev/ttyS0
docker-root login: docker[1]: segfault at 0 ip 00000000006736b0 sp 000000c20825e808 error 6 in docker[400000+1273000]

Welcome to DockerRoot docker-root /dev/ttyS0
```

**Comment by ailispaw** [comment]
I know that segfault, but it doesn't seem harmful.
I have been trying to figure it out.

**Comment by ailispaw** [comment]
For start.sh;

Could you modify vm/Makefile to debug?
Comment out the last three parameters as below.

```
CMDLINE  := earlyprintk=serial console=ttyS0 #console=tty0 quiet loglevel=3
```

And then how do you see messages on boot after `init[1]: Starting custom script start.sh` line on the console?

**Comment by if-kenn** [comment]
debug here:

https://gist.github.com/if-kenn/cd3ff185005b77c618ad

**Comment by ailispaw** [comment]
Thank you for the info.
I saw `mount: mounting 192.168.64.1:/Users on /Users failed: Operation not supported` there.
There is something wrong with NFS server or client.

I would like to make sure that you can re-run the start.sh successfully after boot, can't you?

**Comment by ailispaw** [comment]
The other thing.
I saw;

```
DOCKERROOT-DATA: recovering journal
DOCKERROOT-DATA: clean, 66747/804400 files, 311321/804096 blocks
```

It seems something bad on the last halt, I guess.
Do you have a lot of containers or heavy tasks in a container on your VM?

**Comment by if-kenn** [comment]
Yes, I am able to mount after logging in by either doing it explicitly:

```
sudo mount 192.168.64.1:/Users /Users -o rw,async,noatime,rsize=32768,wsize=32768,nolock,vers=3
```

or running the script myself:

```
sudo /mnt/vda1/var/lib/docker-root/start.sh
```

I wonder if the journal recovery had not completed properly. I only have 4 images locally (3 my own making), and only running 2 images. 

Could it possibly be by a large number of files under /Users?

**Comment by ailispaw** [comment]
Thank you.
Could you put a debug print in the start.sh as below and see how the boot messages will be?

```
#!/bin/sh

mkdir -p /Users
umount /Users
GW_IP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $3}')
if [ -n "${GW_IP}" ]; then
  echo mount ${GW_IP}:/Users /Users -o rw,async,noatime,rsize=32768,wsize=32768,nolock,vers=3
  mount ${GW_IP}:/Users /Users -o rw,async,noatime,rsize=32768,wsize=32768,nolock,vers=3
fi
```

**Comment by if-kenn** [comment]
https://gist.github.com/if-kenn/1fdf8cf247e3c6b979bb

**Comment by ailispaw** [comment]
@if-kenn Thank you so much for your support.
Hmm. That looks good...

**Comment by ailispaw** [comment]
> I wonder if the journal recovery had not completed properly.

I believe the fsck had completed successfully, but I'm concerned about what caused the breakage.
I might be going to revise the shutdown script.

> Could it possibly be by a large number of files under /Users?

No, I don't think so.
I guess that is just a timing.
You may put some sleep before the mount script.
Or you have to specify a format like `mount -t nfs`.
Anyway please give me more time to figure it out.

**Comment by if-kenn** [comment]
For the time being putting "sleep 1" as the first line of /mnt/vda1/var/lib/docker-root/start.sh seems to work.

Specifying the type as NFS doesn't seem to help.

**Comment by ailispaw** [comment]
@if-kenn Thank you so much for your cooperation.
That is very helpful.

**Comment by if-kenn** [comment]
My pleasure, thanks for your work!

**Comment by ailispaw** [comment]
I found a reason why it can not mount on boot.
Restarting NFSD is too slow to mount on boot.
It has to wait for nfsd running before xhyve is executed.
I will patch it.

**Comment by ailispaw** [comment]
I commit the patch https://github.com/ailispaw/docker-root-xhyve/commit/bae9a60a34ea7b31077cc6bfddec1994da260227.
@if-kenn Please check it.

**Comment by ailispaw** [comment]
```
DOCKERROOT-DATA: recovering journal
DOCKERROOT-DATA: clean, 66747/804400 files, 311321/804096 blocks
```

I misunderstood it.
Recovering journal is completed successfully and the filesystem is clean.
It's OK. I leave the shutdown script.

**Comment by if-kenn** [comment]
Thanks!

The patch appears to work, but I think you could switch back to restart from stop/start since that works with the wait loop.

**Comment by ailispaw** [comment]
@if-kenn Thanks for the confirmation.

Yes, I could, but I would like to use stop/start and see progress messages to understand what's going on easily.

**Comment by nightscape** [comment]
I just ran into a similar issue, except that I couldn't mount `/Users` even after the VM had started (`mount: mounting 192.168.64.1:/Users on /Users failed: Permission denied`).
It turns out that in my `/etc/exports` configuration I had two almost identical lines:

```
/Users -network 192.168.64.1 -mask 255.255.255.0 -alldirs -mapall=507:20
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=507:20
```

After deleting both of them and restarting docker-root-xhyve, the Users directory was mounted correctly.

It might be worth adding a `nfsd checkexports` to `xhyverun.sh` which should show the problem (maybe even aborting immediately if there is a problem).

**Comment by ailispaw** [comment]
@nightscape Thank you so much for your report and suggestion.

I had a same issue once before.
The old docker-root-xhyve had a bug which had created the line with `192.168.64.1`.
`192.168.64.0` is the correct one which the new docker-root-xhyve creates but it doesn't clean the `192.168.64.1` line.

I will try to add `nfsd checkexports`.
Thanks.

**Comment by ailispaw** [comment]
And also sometimes the entry in the `/etc/exports` conflicts with others (like what Vagrant creates automatically).

**Comment by ailispaw** [comment]
@nightscape Done.
Thank you so much for your advice.

**Comment by nightscape** [comment]
@ailispaw Thank you so much for developing this blazing fast VM :racehorse:

**Comment by nightscape** [comment]
@if-kenn From my point of view, this issue can be closed.

**Comment by if-kenn** [comment]
@nightscape your right, I will close it.

**Comment by if-kenn** [comment]
@ailispaw I also want to again thank you and echo @nightscape appreciation.

**Comment by ailispaw** [comment]
@if-kenn @nightscape Thank you so much!
I'm happy you like DockerRoot.
