### ISSUE TITLE
kernel panic from "shutdown -r now"

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root-xhyve#3]
When issuing:

`sudo shutdown -r now`

I get the following:

```
rdmsr to register 0x570 on vcpu 0
                                 Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100

Kernel Offset: disabled
---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
```

The vm appears to go into a broken state and can no longer function.

**Comment by if-kenn** [comment]
When trying to do a "make up" or "sudo ./xhyverun.sh " I am now getting:

```
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
```

This is even after rebooting the Mac and  blowing away the docker-root-xhyve and cloning again. Is this a possible Mac OSX 10.11.1 change?

**Comment by ailispaw** [comment]
Hi @if-kenn ,

Which version of DockerRoot do you use?
I updated DockerRoot to v1.0.10 last night. Did you update this repo before?
Had the old versions worked well?

I guess you may need to re-build xhyve and uuid2mac on Mac OSX 10.11.1, because that message is related to vmnet.framework in OSX.

**Comment by ailispaw** [comment]
You can try older version of DockerRoot by editing the line https://github.com/ailispaw/docker-root-xhyve/blob/master/vm/Makefile#L17 and `make clean && make init`.

**Comment by ailispaw** [comment]
And also please take a look at the following files related to vmnet.framework in your OSX.
/var/db/dhcpd_leases
/Library/Preferences/SystemConfiguration/com.apple.vmnet.plist

**Comment by ailispaw** [comment]
Let me see again...
docker-root-xhyve were running and you tried to reboot `sudo shutdown -r now`.
And then it got the panic.
It means you could `make up` before the panic, right?

Did you do something during the docker-root-xhyve running?

**Comment by if-kenn** [comment]
I am now getting this on both OSX 10.10 and 10.11. On 10.11 it happened after (note it was a halt):

```
sudo shutdown -h now
```

On 10.10 it was after (note it was a restart):

```
sudo shutdown -r now
```

Only thing that changed was adding a INSECURE_REGISTRY to /var/lib/docker-root/profile

I have tried to downgrade the DockerRoot all the way back to 1.0.6 in the Makefile, do a "make clean" and "make init" but still the same result.

One thing to note is during "make init" I see this:

```
ld uuid2mac.sym
ld: warning: object file (build/uuid2mac.lto.o) was built for newer OSX version (10.10) than being linked (0.46.52)
dsym uuid2mac.dSYM
```

**Comment by if-kenn** [comment]
contents of /var/db/dhcpd_leases:

```
{
    name=docker-root
    ip_address=192.168.64.2
    hw_address=1,32:70:cb:56:cf:32
    identifier=1,32:70:cb:56:cf:32
    lease=0x56315608
}
```

contents of /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>MAC_ARRAY</key>
        <array>
                <dict>
                        <key>MAC_ADDRESS</key>
                        <data>
                        MnDLVs8y
                        </data>
                        <key>MAC_TIME_USED</key>
                        <date>2015-10-27T23:10:55Z</date>
                        <key>MAC_USED</key>
                        <true/>
                        <key>UUID_MAC</key>
                        <string>5CB21FA0-193A-5947-A47A-2E353E51807D</string>
                </dict>
        </array>
        <key>MAC_IOUE_ARRAY</key>
        <array>
                <dict>
                        <key>MAC_IOUE</key>
                        <data>
                        TlQUuMps
                        </data>
                        <key>MAC_IOUE_USED</key>
                        <true/>
                </dict>
        </array>
        <key>Shared_Net_Address</key>
        <string>192.168.64.1</string>
        <key>Shared_Net_Mask</key>
        <string>255.255.255.0</string>
</dict>
</plist>
```

**Comment by ailispaw** [comment]
May I have your modified `/var/lib/docker-root/profile`?
I guess there is an invalid parameter for Docker in there.

**Comment by ailispaw** [comment]
@if-kenn Thanks. Those files look good.

**Comment by if-kenn** [comment]
Shouldn't a make clean & init throw out any changes to the `/var/lib/docker-root/profile`?

**Comment by if-kenn** [comment]
I have blown away the whole docker-root-xhyve directory and cloned again to have the same panic.

**Comment by ailispaw** [comment]
Hmm... I see.

**Comment by if-kenn** [comment]
Let me reconfirm now.

**Comment by ailispaw** [comment]
Could you get debug messages on boot as same as before?
https://github.com/ailispaw/docker-root-xhyve/issues/1#issuecomment-143087038

**Comment by if-kenn** [comment]
This is from a complete remove and re-cloning.

Listing complete repro steps:

```
Kenns-MacBook-Pro:src kenn$ ls -l
total 6496
drwxr-xr-x  11 kenn  staff      374 Oct 27 09:58 docker-root-xhyve
drwxr-xr-x  12 kenn  staff      408 Oct  1 13:41 docker-root-xhyve.bak
-rw-r--r--   1 kenn  staff  3249343 Aug 19 14:36 drupal-7.39.tar.gz
-rw-r--r--   1 kenn  staff    49253 Aug 31 01:49 redis-7.x-3.11.tar.gz
-rw-r--r--   1 kenn  staff    16671 Sep 11  2014 varnish-7.x-1.0-beta3.tar.gz
Kenns-MacBook-Pro:src kenn$ rm -rf docker-root-xhyve*
Kenns-MacBook-Pro:src kenn$ mkdir ~/fulcrum/src/docker-root-xhyve
Kenns-MacBook-Pro:src kenn$ cd ~/fulcrum/src/docker-root-xhyve
Kenns-MacBook-Pro:docker-root-xhyve kenn$ git clone https://github.com/ailispaw/docker-root-xhyve .
Cloning into '.'...
remote: Counting objects: 277, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 277 (delta 5), reused 0 (delta 0), pack-reused 259
Receiving objects: 100% (277/277), 37.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (141/141), done.
Checking connectivity... done.
Kenns-MacBook-Pro:docker-root-xhyve kenn$ make init
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   592    0   592    0     0   1021      0 --:--:-- --:--:-- --:--:--  1020
100 12.0M  100 12.0M    0     0  1111k      0  0:00:11  0:00:11 --:--:-- 2706k
/dev/disk7                                              /Volumes/DOCKER_ROOT
hdiutil: unmount: LetIOKitSettleDown: (timed out)
"/Volumes/DOCKER_ROOT" unmounted successfully.
/dev/disk7                                              /Volumes/DOCKER_ROOT
hdiutil: unmount: LetIOKitSettleDown: (timed out)
"/Volumes/DOCKER_ROOT" unmounted successfully.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    545      0 --:--:--  0:00:01 --:--:--   545
100 4084k  100 4084k    0     0  1000k      0  0:00:04  0:00:04 --:--:-- 1374k
x docker-root-data.img
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C uuid2mac
cc main.c
ld uuid2mac.sym
ld: warning: object file (build/uuid2mac.lto.o) was built for newer OSX version (10.10) than being linked (0.46.52)
dsym uuid2mac.dSYM
strip uuid2mac
install: uuid2mac/build/uuid2mac -> bin//uuid2mac
Kenns-MacBook-Pro:docker-root-xhyve kenn$ make up
Password:
Sorry, try again.
Password:
Booting up...
Kenns-MacBook-Pro:docker-root-xhyve kenn$
```

Then when iTerm screen splits:

```
Last login: Tue Oct 27 16:19:31 on ttys001
Kenns-MacBook-Pro:~ kenn$ cd '/Users/kenn/fulcrum/src/docker-root-xhyve'; sudo ./xhyverun.sh && exit
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
Kenns-MacBook-Pro:docker-root-xhyve kenn$
```

**Comment by if-kenn** [comment]
Does not even seem to get to kernel panic.

**Comment by if-kenn** [comment]
FYI, using xhyve from `brew install xhyve`.

**Comment by ailispaw** [comment]
> virtio_net: Could not create vmnet interface, permission denied or no entitlement?

Are Dead xhyve processes still running somewhere?

**Comment by ailispaw** [comment]
It's a different case from kernel panic.

**Comment by if-kenn** [comment]
Yes should I kill?

```
Kenns-MacBook-Pro:docker-root-xhyve kenn$ ps auxw |grep xhyve|grep -v grep
root            16880 100.0  0.1  3558912  19400   ??  R     4:10PM  31:32.66 xhyve -A -m 1G -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 2:0,virtio-net -s 4,virtio-blk,/Users/kenn/fulcrum/src/docker-root-xhyve/vm/docker-root-data.img -U A01FB25C-3A19-4759-A47A-2E353E51807D -f kexec,/Users/kenn/fulcrum/src/docker-root-xhyve/vm/bzImage,/Users/kenn/fulcrum/src/docker-root-xhyve/vm/initrd,earlyprintk=serial console=ttyS0 console=tty0 quiet loglevel=3 docker-root.nfsroot="/Users/kenn"
root            16809   0.0  0.0  2446680   1116   ??  S     4:10PM   0:00.02 /bin/sh ./xhyverun.sh
root            16808   0.0  0.0  2460804   2660   ??  S     4:10PM   0:00.01 sudo ./xhyverun.sh
Kenns-MacBook-Pro:docker-root-xhyve kenn$
```

**Comment by ailispaw** [comment]
Yes, you should, whenever you got an error with xhyve.

**Comment by if-kenn** [comment]
OK, killed all three processes and have a live VM. Will restart to see if kernel panic happens.

**Comment by if-kenn** [comment]
Kernel panic did **not** happen. Wondering is this is connected by me corrupting `/var/lib/docker-root/profile` and that causing xhyve to hang around preventing ability to setup virtio_net.

**Comment by ailispaw** [comment]
There are two cases here and they are not related directly.

One: If docker exits by mistake, it goes kernel panic, because Docker runs as PID 1 on DockerRoot.

Two: If xhyve process with the same UUID runs, another xhyverun.sh will have a virtio_net error.

**Comment by ailispaw** [comment]
But I'm concerned about the case of `sudo shutdown -h now` on 10.11.
A kernel panic happened on halt?

**Comment by if-kenn** [comment]
I think it might of been from me messing up the docker-root profile. I am going to try and get it working OK on 10.10 and then will look at 10.11.

**Comment by ailispaw** [comment]
Thanks.

**Comment by ailispaw** [comment]
I have started thinking Docker is not good for PID 1 on DockerRoot unlike RancherOS.

**Comment by if-kenn** [comment]
OK, I believe that not having the insecure registry quoted in the docker profile caused the kernel panic which in turn left xhyve hanging around on the Mac. It is now working on 10.10 and 10.11.

Are you thinking that PID 1 is not a good idea because of these types of things that it can't recover from?

Thanks for all your attention.

**Comment by ailispaw** [comment]
Yes, I am.
Docker as PID 1 is originally from RancherOS, but it's not beneficial of DockerRoot so far, it's just a design now.

**Comment by ailispaw** [comment]
@if-kenn Anyway, thank you so much for your confirmation.
Please close it, if you're OK.

**Comment by if-kenn** [comment]
Again thank you so much!

**Comment by ailispaw** [comment]
@if-kenn 
I have released DockerRoot v1.0.11.
With v1.0.11, if you have a kernel panic like this, you can append `docker-root.debug` in the kernel boot parameter line at https://github.com/ailispaw/docker-root-xhyve/blob/master/vm/Makefile#L3.
And then after the next boot, it should boot up normally, but it may not have Docker daemon process.
You can check log files, `/var/lib/docker-root/docker.log` and `/var/log/message` for debug.

Even more,
on this debug mode, you can use `/etc/init.d/docker` to start/stop/restart the Docker daemon without reboot.

**Comment by if-kenn** [comment]
Great news!

FYI, I am making a LEMP dev stack that might be a nice test piece for your system, let me know if you are interested in it for testing when it is solid and I can abstract it.

**Comment by ailispaw** [comment]
Sounds good. Does it work with docker-compose or something?
I have just some simple tests with Vagrant like https://github.com/ailispaw/consul-cluster.
Let me try.
Thanks in advance.

**Comment by if-kenn** [comment]
Right now it is simply scripts, but I will look towards compose soon.

**Comment by ailispaw** [comment]
Sounds nice!
