### ISSUE TITLE
Allocate more than 999.9MB

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root-xhyve#4]
Is there somewhere to up the amount of memory that DockerRoot is allocated? I have started to run out of memory with Nginx, PHP-FPM and MariaDB running and I still want to add in Redis and Varnish.

**Comment by ailispaw** [comment]
By default, it's set 1GB, but you can set any value at this line.
https://github.com/ailispaw/docker-root-xhyve/blob/master/xhyverun.sh#L12

**Comment by if-kenn** [comment]
Ha, literally just found it as you wrote this!

**Comment by if-kenn** [comment]
looks like it worked
