### ISSUE TITLE
Feature request: Startup

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root-xhyve#5]
I am currently issuing a few commands that I find helpful after initial creation and others might as well:

```
# setup a .ssh directory with proper perms
ssh docker@$(make ip) ssh-keygen -t rsa

# copy public key to the authorized keys for no password ssh/scp/etc
scp ~/.ssh/id_rsa.pub docker@$(make ip):.ssh/authorized_keys

# add docker extra args
ssh docker@$(make ip) 'echo "DOCKER_EXTRA_ARGS=\"--insecure-registry dockreg.example.net:5000\"" | sudo tee -a /var/lib/docker-root/profile'

```

**Comment by ailispaw** [comment]
If you want to just add docker extra args, you can do as below.

```
make ssh 'echo "DOCKER_EXTRA_ARGS=\"--insecure-registry dockreg.example.net:5000\"" | sudo tee -a /var/lib/docker-root/profile'
```

**Comment by ailispaw** [comment]
Oops. It's wrong.

**Comment by if-kenn** [comment]
The above was mainly for the password-less setup. The DOCKER_EXTRA_ARGS was sugar.

**Comment by if-kenn** [comment]
Was thinking it could be added to the Makefile, e.g. "make nopasswordlogin"

**Comment by ailispaw** [comment]
Yeah, it could be useful, but I think it is not good for everyone.
The ssh key should be at a different place instead of ~/.ssh.
Let me think.

**Comment by ailispaw** [comment]
Makefile doesn't seem good for it. I think we need a script like https://github.com/nlf/dhyve.

**Comment by ailispaw** [comment]
It would be at `contrib` directory. I will consider it more later. Thanks.

**Comment by if-kenn** [comment]
Good thinking.

**Comment by ailispaw** [comment]
I have changed my mind and put scripts on `./bin`.
Your idea is great!

Now you can customize Docker daemon as below.

```
$ make run
$ bin/setsshkey.sh
$ bin/ssh.sh 'echo "DOCKER_EXTRA_ARGS=\"--insecure-registry dockreg.example.net:5000\"" | sudo tee -a /var/lib/docker-root/profile'
$ bin/ssh.sh 'sudo /etc/init.d/docker restart'
```

**Comment by if-kenn** [comment]
That is great to hear!

**Comment by if-kenn** [comment]
It would also be ideal that when running "make run" that it checks to make sure there is not a boot2docker running and if there is fail out with a warning message. As I was getting one of my engineers up on the env, it kept on hard crashing his Mac.

**Comment by ailispaw** [comment]
He might have the older VirtualBox with boot2docker and needs VirtualBox v5.0 or later.

**Comment by ailispaw** [comment]
I may be able to check the version of VirtualBox instead.

```
$ VBoxManage --version
5.0.8r103449
```
