### ISSUE TITLE
Add instructions for upgrading

### ISSUE THREAD

**Issue by nightscape** [ailispaw/docker-root-xhyve#6]
Hi @ailispaw,

it would be great if you could add some info to the README on how to best upgrade the image,
especially if one increased the disk size of the `.img` file.
Currently, I'm doing something along the lines of

```
cd vm
mv docker-root-data.img ..
rm bzImage initrd docker-root.iso docker-root-data.tar.gz
make
mv ../docker-root-data.img .
```

but this is rather cumbersome and does not upgrade the `docker-root-data.img` file which might be a bad thing...
Is there a better way for upgrading the docker-root image?

**Comment by ailispaw** [comment]
Hi @nightscape ,

Do you mean this https://github.com/ailispaw/docker-root-xhyve/blob/master/contrib/resizehdd.md ?

Or when docker-root.iso is upgraded?
It is supposed to be unnecessary to upgrade docker-root-data.img.

However I will consider the better way to upgrade docker-root.iso easily.
Thank you for your suggestion.

**Comment by ailispaw** [comment]
Oh, I see. When docker-root-data.tar.gz is upgraded or patched, you need to upgrade the image, right.
Let me think about that, too.

**Comment by ailispaw** [comment]
Hmm... It doesn't seem so easy for `.img`.

Case 1: when docker-root.iso is upgraded,

```
$ git pull origin master
$ rm vm/docker-root.iso
$ make
```

Case 2: when you make or resize an HDD, follow the instructions below.
https://github.com/ailispaw/docker-root-xhyve/tree/master/contrib/makehdd
https://github.com/ailispaw/docker-root-xhyve/blob/master/contrib/resizehdd.md

Case 3: when docker-root-data.tar.gz is upgraded or patched, it can't be updated automatically anyway. But it's **_very rare**_ and I don't have any plan to update the image.

**Comment by ailispaw** [comment]
I have added `make upgrade` target to upgrade DockerRoot.
https://github.com/ailispaw/docker-root-xhyve/commit/73690a5f374f5a8225bfde0dc18d9b3ec47c2457
It may be useful for case 1 above.

**Comment by nightscape** [comment]
Ok, then Case 1 is what I needed, thanks for the patch!
I just wasn't sure if the `.img` needs to be updated as well if a new version of `docker-root.iso` is used, but your explanation clarified that :)
Thanks again!
