### ISSUE TITLE
Windows alternative?

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root-xhyve#7]
We have the need to be able to show some clients how to have a Docker setup on Windows. I have looked a bit and trying to find a similar setup to running xhyve and DockerRoot on Windows but have not found anything. My intention is to try and have it as light weight as possible and not need to have VirtualBox sitting in the middle of the setup. Have you seen anything I should look at?

**Comment by ailispaw** [comment]
Hi @if-kenn, 
I don't have much experience on Windows and don't have Windows PC now.
But it might be Hyper-V, I guess.
boot2docker supports Hyper-V as well as VirtualBox, Parallels, VMware and XenServer.
Therefore, DockerRoot might be able to support Hyper-V, though I don't know how so far.

**Comment by if-kenn** [comment]
Ya, I haven't done anything with Windows in more than a decade. Thanks, will check it out when I get a chance. Will let you know if I got anywhere.

**Comment by ailispaw** [comment]
Boot2Docker on Hyper-V | Chris Swan's Weblog
http://blog.thestateofme.com/2014/02/18/boot2docker-on-hyper-v/

Getting Docker Running on Hyper-V 8.1/ 2012 R2 - Shawn Cicoria - Site Home - MSDN Blogs
http://blogs.msdn.com/b/scicoria/archive/2014/10/09/getting-docker-running-on-hyper-v-8-1-2012-r2.aspx

**Comment by ailispaw** [comment]
This repo is responsible for Mac OSX because of xhyve.
Closing.
