### ISSUE TITLE
API mismatch Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)

### ISSUE THREAD

**Issue by wadkar** [ailispaw/docker-root-xhyve#9]
First of all, thanks for the work on docker-root

The docker server installed in the VM is 1.9.1 with API version 1.21:

``` sh
[docker@docker-root ~]$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   66c06d0-stripped
 Built:        Sun Jan 24 07:17:18 UTC 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   66c06d0-stripped
 Built:        Sun Jan 24 07:17:18 UTC 2016
 OS/Arch:      linux/amd64
```

Turns out that `brew install docker` pulls in docker client version 1.10.3 with API version 1.22

``` sh
$ brew info docker
docker: stable 1.10.3 (bottled), HEAD
...
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64
Error response from daemon: client is newer than server (client API version: 1.22, server API version: 1.21)
```

Currently, I am using the docker client inside the VM, but ideally I would prefer to use the native/brew docker client. I checked `brew tap homebrew/versions` for a previous version of docker191, but that specific version isn't tapped (yet).

Suggestions/workaround/fix?

**Comment by ailispaw** [comment]
@wadkar 
If you have DockerRoot v1.3.2 or later, you can install any version of Docker in the VM as below.

```
[docker@docker-root ~]$ sudo /etc/init.d/docker restart v1.10.3
```

https://github.com/ailispaw/docker-root#features

**Comment by wadkar** [comment]
Thanks!
